import { ReservationDetails, UserSpaceReservation } from "../misc/model/reservation.model"

export const  reservation_details: ReservationDetails[]  = 
[
  {
      ReservationId: 1,
      ParkingSpaceId: 1001,
      PeopleKey: 600617,
      ReservationStartDateTime: new Date ("11/09/2023 23:40"),
      ReservationEndDateTime: new Date ("11/10/2023 2:00"),
      DayofWeek: "Friday",
      PlateNbr: "ABC-234",
      ReservationStatus: "Completed"
  },
  {
      ReservationId: 2,
      ParkingSpaceId: 1002,
      PeopleKey: 600617,
      ReservationStartDateTime: new Date ("11/10/2023 8:00 AM"),
      ReservationEndDateTime: new Date ("11/10/2023 19:00"),
      DayofWeek: "Friday",
      PlateNbr: "ABC-234",
      ReservationStatus: "Completed"
  },
//   {
//       ReservationId: 3,
//       ParkingSpaceId: 2001,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("11/11/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/11/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 4,
//       ParkingSpaceId: 2002,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("11/12/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/12/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 5,
//       ParkingSpaceId: 3001,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("11/13/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/13/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 6,
//       ParkingSpaceId: 3002,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("11/14/2023 23:59"),
//       ReservationEndDateTime: new Date ("11/15/2023 02:00"),
//       DayofWeek: "Tuesday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 7,
//       ParkingSpaceId: 4001,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("11/15/2023 10:00 AM"),
//       ReservationEndDateTime: new Date ("11/15/2023 7:00 PM"),
//       DayofWeek: "Wednesday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 8,
//       ParkingSpaceId: 4002,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("11/16/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/16/2023 19:00"),
//       DayofWeek: "Thursday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 9,
//       ParkingSpaceId: 5001,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("11/17/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/17/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 10,
//       ParkingSpaceId: 5002,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("11/18/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/18/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 11,
//       ParkingSpaceId: 7001,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("11/9/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/9/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 12,
//       ParkingSpaceId: 7002,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("11/10/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/10/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 13,
//       ParkingSpaceId: 7001,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("11/11/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/11/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 14,
//       ParkingSpaceId: 7002,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("11/12/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/12/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 15,
//       ParkingSpaceId: 7001,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("11/13/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/13/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 16,
//       ParkingSpaceId: 7002,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("11/14/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/14/2023 19:00"),
//       DayofWeek: "Tuesday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 17,
//       ParkingSpaceId: 7001,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("11/15/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/15/2023 19:00"),
//       DayofWeek: "Wednesday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 18,
//       ParkingSpaceId: 7002,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("11/16/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/16/2023 19:00"),
//       DayofWeek: "Thursday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 19,
//       ParkingSpaceId: 5001,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("11/17/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/17/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 20,
//       ParkingSpaceId: 7002,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("11/18/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/18/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 21,
//       ParkingSpaceId: 1001,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("11/9/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/9/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 22,
//       ParkingSpaceId: 1002,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("11/10/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/10/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 23,
//       ParkingSpaceId: 2001,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("11/11/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/11/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 24,
//       ParkingSpaceId: 2002,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("11/12/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/12/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 25,
//       ParkingSpaceId: 3001,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("11/13/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/13/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 26,
//       ParkingSpaceId: 3002,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("11/14/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/14/2023 19:00"),
//       DayofWeek: "Tuesday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 27,
//       ParkingSpaceId: 4001,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("11/15/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/15/2023 19:00"),
//       DayofWeek: "Wednesday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 28,
//       ParkingSpaceId: 4002,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("11/16/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/16/2023 19:00"),
//       DayofWeek: "Thursday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 29,
//       ParkingSpaceId: 5001,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("11/17/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/17/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 30,
//       ParkingSpaceId: 5002,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("11/18/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/18/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 31,
//       ParkingSpaceId: 7001,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("12/9/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/9/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 32,
//       ParkingSpaceId: 7002,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("12/10/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/10/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 33,
//       ParkingSpaceId: 7001,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("12/11/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/11/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 34,
//       ParkingSpaceId: 7002,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("12/12/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/12/2023 19:00"),
//       DayofWeek: "Tuesday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 35,
//       ParkingSpaceId: 7001,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("12/13/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/13/2023 19:00"),
//       DayofWeek: "Wednesday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 36,
//       ParkingSpaceId: 7002,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("12/14/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/14/2023 19:00"),
//       DayofWeek: "Thursday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 37,
//       ParkingSpaceId: 7001,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("12/15/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/15/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 38,
//       ParkingSpaceId: 7002,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("12/16/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/16/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 39,
//       ParkingSpaceId: 7001,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("12/17/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/17/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 40,
//       ParkingSpaceId: 7002,
//       PeopleKey: 723544,
//       ReservationStartDateTime: new Date ("12/18/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/18/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "AAA-543",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 41,
//       ParkingSpaceId: 1001,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("12/9/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/9/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 42,
//       ParkingSpaceId: 1002,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("12/10/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/10/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 43,
//       ParkingSpaceId: 2001,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("12/11/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/11/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 44,
//       ParkingSpaceId: 2002,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("12/12/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/12/2023 19:00"),
//       DayofWeek: "Tuesday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 45,
//       ParkingSpaceId: 3001,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("12/13/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/13/2023 19:00"),
//       DayofWeek: "Wednesday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 46,
//       ParkingSpaceId: 3002,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("12/14/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/14/2023 19:00"),
//       DayofWeek: "Thursday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 47,
//       ParkingSpaceId: 4001,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("12/15/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/15/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 48,
//       ParkingSpaceId: 4002,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("12/16/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/16/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 49,
//       ParkingSpaceId: 5001,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("12/17/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/17/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 50,
//       ParkingSpaceId: 5002,
//       PeopleKey: 617999,
//       ReservationStartDateTime: new Date ("12/18/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/18/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "XZY-123",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 51,
//       ParkingSpaceId: 7001,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("12/9/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/9/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 52,
//       ParkingSpaceId: 7002,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("12/10/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/10/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 53,
//       ParkingSpaceId: 7001,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("12/11/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/11/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 54,
//       ParkingSpaceId: 7002,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("12/12/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/12/2023 19:00"),
//       DayofWeek: "Tuesday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 55,
//       ParkingSpaceId: 7001,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("12/13/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/13/2023 19:00"),
//       DayofWeek: "Wednesday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 56,
//       ParkingSpaceId: 7002,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("12/14/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/14/2023 19:00"),
//       DayofWeek: "Thursday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 57,
//       ParkingSpaceId: 7001,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("12/15/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/15/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 58,
//       ParkingSpaceId: 7002,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("12/16/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/16/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 59,
//       ParkingSpaceId: 7001,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("12/17/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/17/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 60,
//       ParkingSpaceId: 7002,
//       PeopleKey: 600617,
//       ReservationStartDateTime: new Date ("12/18/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/18/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "ABC-234",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 61,
//       ParkingSpaceId: 1001,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("11/9/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/9/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 62,
//       ParkingSpaceId: 1002,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("11/10/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/10/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 63,
//       ParkingSpaceId: 2001,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("11/11/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/11/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 64,
//       ParkingSpaceId: 2002,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("11/12/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/12/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 65,
//       ParkingSpaceId: 3001,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("11/13/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/13/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 66,
//       ParkingSpaceId: 3002,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("11/14/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/14/2023 19:00"),
//       DayofWeek: "Tuesday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 67,
//       ParkingSpaceId: 4001,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("11/15/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/15/2023 19:00"),
//       DayofWeek: "Wednesday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 68,
//       ParkingSpaceId: 4002,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("11/16/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/16/2023 19:00"),
//       DayofWeek: "Thursday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 69,
//       ParkingSpaceId: 5001,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("11/17/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/17/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 70,
//       ParkingSpaceId: 5002,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("11/18/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/18/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 71,
//       ParkingSpaceId: 7001,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("12/9/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/9/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 72,
//       ParkingSpaceId: 7002,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("12/10/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/10/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 73,
//       ParkingSpaceId: 7001,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("12/11/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/11/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 74,
//       ParkingSpaceId: 7002,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("12/12/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/12/2023 19:00"),
//       DayofWeek: "Tuesday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 75,
//       ParkingSpaceId: 7001,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("12/13/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/13/2023 19:00"),
//       DayofWeek: "Wednesday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 76,
//       ParkingSpaceId: 7002,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("12/14/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/14/2023 19:00"),
//       DayofWeek: "Thursday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 77,
//       ParkingSpaceId: 7001,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("12/15/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/15/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 78,
//       ParkingSpaceId: 7002,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("12/16/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/16/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 79,
//       ParkingSpaceId: 7001,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("12/17/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/17/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 80,
//       ParkingSpaceId: 7002,
//       PeopleKey: 788442,
//       ReservationStartDateTime: new Date ("12/18/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/18/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "KGE-990",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 81,
//       ParkingSpaceId: 1001,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("11/9/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/9/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 82,
//       ParkingSpaceId: 1002,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("11/10/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/10/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 83,
//       ParkingSpaceId: 2001,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("11/11/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/11/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 84,
//       ParkingSpaceId: 2002,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("11/12/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/12/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 85,
//       ParkingSpaceId: 3001,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("11/13/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/13/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 86,
//       ParkingSpaceId: 3002,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("11/14/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/14/2023 19:00"),
//       DayofWeek: "Tuesday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 87,
//       ParkingSpaceId: 4001,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("11/15/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/15/2023 19:00"),
//       DayofWeek: "Wednesday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 88,
//       ParkingSpaceId: 4002,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("11/16/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/16/2023 19:00"),
//       DayofWeek: "Thursday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 89,
//       ParkingSpaceId: 5001,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("11/17/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/17/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 90,
//       ParkingSpaceId: 5002,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("11/18/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("11/18/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 91,
//       ParkingSpaceId: 7001,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("12/9/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/9/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 92,
//       ParkingSpaceId: 7002,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("12/10/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/10/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 93,
//       ParkingSpaceId: 7001,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("12/11/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/11/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 94,
//       ParkingSpaceId: 7002,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("12/12/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/12/2023 19:00"),
//       DayofWeek: "Tuesday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 95,
//       ParkingSpaceId: 7001,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("12/13/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/13/2023 19:00"),
//       DayofWeek: "Wednesday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 96,
//       ParkingSpaceId: 7002,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("12/14/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/14/2023 19:00"),
//       DayofWeek: "Thursday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Canceled"
//   },
//   {
//       ReservationId: 97,
//       ParkingSpaceId: 7001,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("12/15/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/15/2023 19:00"),
//       DayofWeek: "Friday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 98,
//       ParkingSpaceId: 7002,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("12/16/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/16/2023 19:00"),
//       DayofWeek: "Saturday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 99,
//       ParkingSpaceId: 7001,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("12/17/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/17/2023 19:00"),
//       DayofWeek: "Sunday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Completed"
//   },
//   {
//       ReservationId: 100,
//       ParkingSpaceId: 7002,
//       PeopleKey: 864534,
//       ReservationStartDateTime: new Date ("12/18/2023 8:00 AM"),
//       ReservationEndDateTime: new Date ("12/18/2023 19:00"),
//       DayofWeek: "Monday",
//       PlateNbr: "HRT-322",
//       ReservationStatus: "Canceled"
//   }
]

export const  user_space_reservation: UserSpaceReservation[]  = 
[
    {
        ReservationId: 1,
        DatabaseName: "VD802444",
        WindowsVerion: "11", 
        SQLVersion: "14", 
        CPU: "core 32",
        Memory: 16,
        Type: "database",
        Insights: `Based on the provided data, here are some insights:

        1. The server experiences periods of high CPU idle percentage, indicating low usage and available resources.
        2. There are specific time periods where the CPU idle percentage drops, suggesting increased workload or higher usage.
        3. Monitoring the CPU idle percentage can help identify patterns and potential performance issues.
        4. It is important to investigate the reasons behind the drops in CPU idle percentage during certain time periods to ensure optimal performance.
        5. Analyzing historical data can provide valuable insights into the usage patterns and help optimize resource allocation.
        
        Please let me know if there is anything specific you would like to know or if there are any other insights you would like me to provide.`,
        Health: "Critical",
    },
    {
        ReservationId: 2,
        DatabaseName: "VD811111",
        WindowsVerion: "11", 
        SQLVersion: "14", 
        CPU: "core 32",
        Memory: 16,
        Type: "database",
        Insights: `Based on the provided data, here are some insights:

        1. The server experiences periods of high CPU idle percentage, indicating low usage and available resources.
        2. There are specific time periods where the CPU idle percentage drops, suggesting increased workload or higher usage.
        3. Monitoring the CPU idle percentage can help identify patterns and potential performance issues.
        4. It is important to investigate the reasons behind the drops in CPU idle percentage during certain time periods to ensure optimal performance.
        5. Analyzing historical data can provide valuable insights into the usage patterns and help optimize resource allocation.
        
        Please let me know if there is anything specific you would like to know or if there are any other insights you would like me to provide.`,
        Health: "Critical",
        Recommendations: `Based on the provided data, here are some recommendations:

        1. leroum 
        2. leroum 
        `
    },
    {
        ReservationId: 1,
        DatabaseName: "VD824444",
        WindowsVerion: "11", 
        SQLVersion: "14", 
        CPU: "core 32",
        Memory: 16,
        Type: "database",
        Health: "Critical"
    },
    {
        ReservationId: 3,        
        DatabaseName: "VA801267",
        WindowsVerion: "11", 
        SQLVersion: "16", 
        CPU: "core 32",
        Memory: 16,
        Type: "application",
        Health: "Critical"
    },
    {
        ReservationId: 4,        
        DatabaseName: "VW801266",
        WindowsVerion: "11", 
        SQLVersion: "16", 
        CPU: "core 32",
        Memory: 16,
        Type: "web",
        Health: "Critical"
    },
    {
        ReservationId: 4,        
        DatabaseName: "VW801267",
        WindowsVerion: "11", 
        SQLVersion: "16", 
        CPU: "core 32",
        Memory: 16,
        Type: "web",
        Health: "Healthy"
    },
    {
        ReservationId: 4,        
        DatabaseName: "VW801268",
        WindowsVerion: "11", 
        SQLVersion: "16", 
        CPU: "core 32",
        Memory: 16,
        Type: "web",
        Health: "Critical"
    },
    {
        ReservationId: 4,        
        DatabaseName: "VW801269",
        WindowsVerion: "11", 
        SQLVersion: "16", 
        CPU: "core 32",
        Memory: 16,
        Type: "web",
        Health: "Critical"
    },
    // {
    //    ReservationId: 3,
    //     ParkingSpaceId: 5004,
    //     SpaceName: "UT. Slot 4",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Ops",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("11/17/23 5:00"),
    //     ReservationEndDateTime: new Date("11/17/23 12:00"),
    //     EAName: "",
    //     DayofWeek: "Thursday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/17/23 14:00")
        
    // },
    // {
    //    ReservationId: 4,
    //     ParkingSpaceId: 5005,
    //     SpaceName: "UT. Slot 5",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 654449,
    //     LastName: "Alves",
    //     FirstName: "Jose",
    //     Eid: "jose.alves",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/17/23 8:00"),
    //     ReservationEndDateTime: new Date("11/17/23 19:00"),
    //     EAName: "Amor Tan",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "DEF-897",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    // },
    // {
    //    ReservationId: 5,
    //     ParkingSpaceId: 5007,
    //     SpaceName: "UT. Slot 7",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 933449,
    //     LastName: "Gonzaga",
    //     FirstName: "Jes",
    //     Eid: "jes.gonzaga",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/17/23 9:00"),
    //     ReservationEndDateTime: new Date("11/17/23 19:00"),
    //     EAName: "Amor Tan",
    //     DayofWeek: "Monday",
    //     PlateNbr: "ZXY-647",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/17/23 9:00"),
    //     CheckOutDateTime: new Date("11/17/23 15:00")
    // },
    // {
    //    ReservationId: 6,
    //     ParkingSpaceId: 5008,
    //     SpaceName: "UT. Slot 8",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 633477,
    //     LastName: "Navarro",
    //     FirstName: "Ron",
    //     Eid: "ron.navarro",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/17/23 7:00"),
    //     ReservationEndDateTime: new Date("11/17/23 12:00"),
    //     EAName: "",
    //     DayofWeek: "Tuesday",
    //     PlateNbr: "ZZZ-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/17/23 7:00"),
    //     CheckOutDateTime: new Date("11/17/23 14:00")
    // },
    // {
    //    ReservationId: 7,
    //     ParkingSpaceId: 2001,
    //     SpaceName: "CG2. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 2",
    //     PeopleKey: 600617,
    //     LastName: "Cruz",
    //     FirstName: "Alex",
    //     Eid: "alex.cruz",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/11/23 8:00"),
    //     ReservationEndDateTime: new Date("11/11/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "ABC-234",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG2Lvl3.png",
    //     FloorPlanDescription: "CG2 Level 3",
    //     FloorName: "Level 3",
    //     CheckInDateTime: new Date("11/11/23 8:00"),
    //     CheckOutDateTime: new Date("11/11/23 19:00")
    // },
    // {
    //    ReservationId: 8,
    //     ParkingSpaceId: 4002,
    //     SpaceName: "EB3. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Cebu ebloc 3",
    //     PeopleKey: 600617,
    //     LastName: "Cruz",
    //     FirstName: "Alex",
    //     Eid: "alex.cruz",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/16/23 8:00"),
    //     ReservationEndDateTime: new Date("11/16/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Thursday",
    //     PlateNbr: "ABC-234",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Ebloc",
    //     FloorPlanURL: "",
    //     FloorPlanDescription: "",
    //     FloorName: "",
    //     CheckInDateTime: new Date("11/16/23 8:00"),
    //     CheckOutDateTime: new Date("11/16/23 19:00")
    // },
    // {
    //    ReservationId: 9,
    //     ParkingSpaceId: 5001,
    //     SpaceName: "UT. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 600617,
    //     LastName: "Cruz",
    //     FirstName: "Alex",
    //     Eid: "alex.cruz",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/17/23 8:00"),
    //     ReservationEndDateTime: new Date("11/17/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "ABC-234",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/17/23 8:00"),
    //     CheckOutDateTime: new Date("11/17/23 19:00")
    // },
    // {
    //    ReservationId: 10,
    //     ParkingSpaceId: 1001,
    //     SpaceName: "CG1. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 600617,
    //     LastName: "Cruz",
    //     FirstName: "Alex",
    //     Eid: "alex.cruz",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/9/23 23:50"),
    //     ReservationEndDateTime: new Date("11/10/23 2:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "ABC-234",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/9/23 23:50"),
    //     CheckOutDateTime: new Date("11/10/23 2:00")
    // },
    // {
    //    ReservationId: 11,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 617999,
    //     LastName: "Santos",
    //     FirstName: "Quinn",
    //     Eid: "quinn.santos",
    //     CareerLevel: "Associate Director",
    //     ReservationStartDateTime: new Date("11/10/23 8:00"),
    //     ReservationEndDateTime: new Date("11/10/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "XZY-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/10/23 8:00"),
    //     CheckOutDateTime: new Date("11/10/23 19:00")
    // },
    // {
    //    ReservationId: 12,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 617999,
    //     LastName: "Santos",
    //     FirstName: "Quinn",
    //     Eid: "quinn.santos",
    //     CareerLevel: "Associate Director",
    //     ReservationStartDateTime: new Date("11/12/23 8:00"),
    //     ReservationEndDateTime: new Date("11/12/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Sunday",
    //     PlateNbr: "XZY-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/12/23 8:00"),
    //     CheckOutDateTime: new Date("11/12/23 19:00")
    // },
    // {
    //    ReservationId: 13,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 617999,
    //     LastName: "Santos",
    //     FirstName: "Quinn",
    //     Eid: "quinn.santos",
    //     CareerLevel: "Associate Director",
    //     ReservationStartDateTime: new Date("11/14/23 8:00"),
    //     ReservationEndDateTime: new Date("11/14/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Tuesday",
    //     PlateNbr: "XZY-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/14/23 8:00"),
    //     CheckOutDateTime: new Date("11/14/23 19:00")
    // },
    // {
    //    ReservationId: 14,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 617999,
    //     LastName: "Santos",
    //     FirstName: "Quinn",
    //     Eid: "quinn.santos",
    //     CareerLevel: "Associate Director",
    //     ReservationStartDateTime: new Date("11/16/23 8:00"),
    //     ReservationEndDateTime: new Date("11/16/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Thursday",
    //     PlateNbr: "XZY-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/16/23 8:00"),
    //     CheckOutDateTime: new Date("11/16/23 19:00")
    // },
    // {
    //    ReservationId: 15,
    //     ParkingSpaceId: 5001,
    //     SpaceName: "UT. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 617999,
    //     LastName: "Santos",
    //     FirstName: "Quinn",
    //     Eid: "quinn.santos",
    //     CareerLevel: "Associate Director",
    //     ReservationStartDateTime: new Date("10/17/23 8:00"),
    //     ReservationEndDateTime: new Date("10/17/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "XZY-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("10/17/23 8:00"),
    //     CheckOutDateTime: new Date("10/17/23 19:00")
    // },
    // {
    //    ReservationId: 16,
    //     ParkingSpaceId: 3001,
    //     SpaceName: "CG3. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "GS",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("11/13/23 8:00"),
    //     ReservationEndDateTime: new Date("11/13/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Monday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/13/23 8:00"),
    //     CheckOutDateTime: new Date("11/13/23 19:00")
    // },
    // {
    //    ReservationId: 17,
    //     ParkingSpaceId: 2001,
    //     SpaceName: "CG2. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 2",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("11/11/23 8:00"),
    //     ReservationEndDateTime: new Date("11/11/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG2Lvl3.png",
    //     FloorPlanDescription: "CG2 Level 3",
    //     FloorName: "Level 3",
    //     CheckInDateTime: new Date("11/11/23 8:00"),
    //     CheckOutDateTime: new Date("11/11/23 19:00")
    // },
    // {
    //    ReservationId: 18,
    //     ParkingSpaceId: 4001,
    //     SpaceName: "EB3. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "GS",
    //     FacilityName: "Cebu ebloc 3",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("11/15/23 8:00"),
    //     ReservationEndDateTime: new Date("11/15/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Wednesday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Ebloc",
    //     FloorPlanURL: "",
    //     FloorPlanDescription: "",
    //     FloorName: "",
    //     CheckInDateTime: new Date("11/15/23 8:00"),
    //     CheckOutDateTime: new Date("11/15/23 19:00")
    // },
    // {
    //    ReservationId: 19,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("10/18/23 8:00"),
    //     ReservationEndDateTime: new Date("10/18/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Canceled",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("10/18/23 8:00"),
    //     CheckOutDateTime: new Date("10/18/23 19:00")
    // },
    // {
    //    ReservationId: 20,
    //     ParkingSpaceId: 1002,
    //     SpaceName: "CG1. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("11/10/23 8:00"),
    //     ReservationEndDateTime: new Date("11/10/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/10/23 8:00"),
    //     CheckOutDateTime: new Date("11/10/23 19:00")
    // },
    // {
    //    ReservationId: 21,
    //     ParkingSpaceId: 3002,
    //     SpaceName: "CG3. Slot 2",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Ops",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 788442,
    //     LastName: "Tan",
    //     FirstName: "Amor",
    //     Eid: "amor.tan",
    //     CareerLevel: "Team Lead",
    //     ReservationStartDateTime: new Date("11/14/23 8:00"),
    //     ReservationEndDateTime: new Date("11/14/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Tuesday",
    //     PlateNbr: "KGE-990",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/14/23 8:00"),
    //     CheckOutDateTime: new Date("11/14/23 19:00")
    // },
    // {
    //    ReservationId: 22,
    //     ParkingSpaceId: 2002,
    //     SpaceName: "CG2. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Robinson Cybergate 2",
    //     PeopleKey: 788442,
    //     LastName: "Tan",
    //     FirstName: "Amor",
    //     Eid: "amor.tan",
    //     CareerLevel: "Team Lead",
    //     ReservationStartDateTime: new Date("11/12/23 8:00"),
    //     ReservationEndDateTime: new Date("11/12/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Sunday",
    //     PlateNbr: "KGE-990",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG2Lvl3.png",
    //     FloorPlanDescription: "CG2 Level 3",
    //     FloorName: "Level 3",
    //     CheckInDateTime: new Date("11/12/23 8:00"),
    //     CheckOutDateTime: new Date("11/12/23 19:00")
    // },
    // {
    //    ReservationId: 23,
    //     ParkingSpaceId: 4002,
    //     SpaceName: "EB3. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Cebu ebloc 3",
    //     PeopleKey: 788442,
    //     LastName: "Tan",
    //     FirstName: "Amor",
    //     Eid: "amor.tan",
    //     CareerLevel: "Team Lead",
    //     ReservationStartDateTime: new Date("11/16/23 8:00"),
    //     ReservationEndDateTime: new Date("11/16/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Thursday",
    //     PlateNbr: "KGE-990",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Ebloc",
    //     FloorPlanURL: "",
    //     FloorPlanDescription: "",
    //     FloorName: "",
    //     CheckInDateTime: new Date("11/16/23 8:00"),
    //     CheckOutDateTime: new Date("11/16/23 19:00")
    // },
    // {
    //    ReservationId: 24,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 788442,
    //     LastName: "Tan",
    //     FirstName: "Amor",
    //     Eid: "amor.tan",
    //     CareerLevel: "Team Lead",
    //     ReservationStartDateTime: new Date("11/3/23 8:00"),
    //     ReservationEndDateTime: new Date("11/3/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "KGE-990",
    //     ReservationStatus: "Canceled",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/3/23 8:00"),
    //     CheckOutDateTime: new Date("11/3/23 19:00")
    // },
    // {
    //    ReservationId: 25,
    //     ParkingSpaceId: 1002,
    //     SpaceName: "CG1. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 788442,
    //     LastName: "Tan",
    //     FirstName: "Amor",
    //     Eid: "amor.tan",
    //     CareerLevel: "Team Lead",
    //     ReservationStartDateTime: new Date("11/10/23 8:00"),
    //     ReservationEndDateTime: new Date("11/10/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "KGE-990",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/10/23 8:00"),
    //     CheckOutDateTime: new Date("11/10/23 19:00")
    // },
    // {
    //    ReservationId: 26,
    //     ParkingSpaceId: 5001,
    //     SpaceName: "UT. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("10/9/23 8:00"),
    //     ReservationEndDateTime: new Date("10/9/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("10/9/23 8:00"),
    //     CheckOutDateTime: new Date("10/9/23 19:00")
    // },
    // {
    //    ReservationId: 27,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("9/10/23 8:00"),
    //     ReservationEndDateTime: new Date("9/10/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Sunday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("9/10/23 8:00"),
    //     CheckOutDateTime: new Date("9/10/23 19:00")
    // },
    // {
    //    ReservationId: 28,
    //     ParkingSpaceId: 5001,
    //     SpaceName: "UT. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("9/13/23 8:00"),
    //     ReservationEndDateTime: new Date("9/13/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Wednesday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Canceled",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("9/13/23 8:00"),
    //     CheckOutDateTime: new Date("9/13/23 19:00")
    // },
    // {
    //    ReservationId: 29,
    //     ParkingSpaceId: 5001,
    //     SpaceName: "UT. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("9/15/23 8:00"),
    //     ReservationEndDateTime: new Date("9/15/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("9/15/23 8:00"),
    //     CheckOutDateTime: new Date("9/15/23 19:00")
    // },
    // {
    //    ReservationId: 30,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("9/18/23 8:00"),
    //     ReservationEndDateTime: new Date("9/18/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Monday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Canceled",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("9/18/23 8:00"),
    //     CheckOutDateTime: new Date("9/18/23 19:00")
    // },
    // {
    //    ReservationId: 31,
    //     ParkingSpaceId: 3002,
    //     SpaceName: "CG3. Slot 2",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Ops",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/14/23 8:00"),
    //     ReservationEndDateTime: new Date("11/14/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Tuesday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/14/23 8:00"),
    //     CheckOutDateTime: new Date("11/14/23 19:00")
    // },
    // {
    //    ReservationId: 32,
    //     ParkingSpaceId: 2001,
    //     SpaceName: "CG2. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 2",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/11/23 8:00"),
    //     ReservationEndDateTime: new Date("11/11/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG2Lvl3.png",
    //     FloorPlanDescription: "CG2 Level 3",
    //     FloorName: "Level 3",
    //     CheckInDateTime: new Date("11/11/23 8:00"),
    //     CheckOutDateTime: new Date("11/11/23 19:00")
    // },
    // {
    //    ReservationId: 33,
    //     ParkingSpaceId: 4002,
    //     SpaceName: "EB3. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Cebu ebloc 3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/16/23 8:00"),
    //     ReservationEndDateTime: new Date("11/16/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Thursday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Ebloc",
    //     FloorPlanURL: "",
    //     FloorPlanDescription: "",
    //     FloorName: "",
    //     CheckInDateTime: new Date("11/16/23 8:00"),
    //     CheckOutDateTime: new Date("11/16/23 19:00")
    // },
    // {
    //    ReservationId: 34,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/18/23 8:00"),
    //     ReservationEndDateTime: new Date("11/18/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Canceled",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/18/23 8:00"),
    //     CheckOutDateTime: new Date("11/18/23 19:00")
    // },
    // {
    //    ReservationId: 35,
    //     ParkingSpaceId: 1002,
    //     SpaceName: "CG1. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/10/23 8:00"),
    //     ReservationEndDateTime: new Date("11/10/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/10/23 8:00"),
    //     CheckOutDateTime: new Date("11/10/23 19:00")
    // }
]



export const user_space_reservation_admin: UserSpaceReservation[]  = 
[
    // {
    //     ReservationId: 1,
    //     DatabaseName: "VD802444",
    //     WindowsVerion: "11", 
    //     SQLVersion: "14", 
    //     CPU: "core 32",
    //     Memory: 16
    // },
    // {
    //     ReservationId: 2,        
    //     DatabaseName: "VD801267",
    //     WindowsVerion: "11", 
    //     SQLVersion: "16", 
    //     CPU: "core 32",
    //     Memory: 16
    // },
    // {
    //    ReservationId: 3,
    //     ParkingSpaceId: 5004,
    //     SpaceName: "UT. Slot 4",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Ops",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("11/17/23 5:00"),
    //     ReservationEndDateTime: new Date("11/17/23 12:00"),
    //     EAName: "",
    //     DayofWeek: "Thursday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/17/23 14:00")
        
    // },
    // {
    //    ReservationId: 4,
    //     ParkingSpaceId: 5005,
    //     SpaceName: "UT. Slot 5",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 654449,
    //     LastName: "Alves",
    //     FirstName: "Jose",
    //     Eid: "jose.alves",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/17/23 8:00"),
    //     ReservationEndDateTime: new Date("11/17/23 19:00"),
    //     EAName: "Amor Tan",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "DEF-897",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    // },
    // {
    //    ReservationId: 5,
    //     ParkingSpaceId: 5007,
    //     SpaceName: "UT. Slot 7",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 933449,
    //     LastName: "Gonzaga",
    //     FirstName: "Jes",
    //     Eid: "jes.gonzaga",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/17/23 9:00"),
    //     ReservationEndDateTime: new Date("11/17/23 19:00"),
    //     EAName: "Amor Tan",
    //     DayofWeek: "Monday",
    //     PlateNbr: "ZXY-647",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/17/23 9:00"),
    //     CheckOutDateTime: new Date("11/17/23 15:00")
    // },
    // {
    //    ReservationId: 6,
    //     ParkingSpaceId: 5008,
    //     SpaceName: "UT. Slot 8",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 633477,
    //     LastName: "Navarro",
    //     FirstName: "Ron",
    //     Eid: "ron.navarro",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/17/23 7:00"),
    //     ReservationEndDateTime: new Date("11/17/23 12:00"),
    //     EAName: "",
    //     DayofWeek: "Tuesday",
    //     PlateNbr: "ABC-234",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/17/23 7:00"),
    //     CheckOutDateTime: new Date("11/17/23 14:00")
    // },
    // {
    //    ReservationId: 7,
    //     ParkingSpaceId: 2001,
    //     SpaceName: "CG2. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 2",
    //     PeopleKey: 600617,
    //     LastName: "Cruz",
    //     FirstName: "Alex",
    //     Eid: "alex.cruz",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/11/23 8:00"),
    //     ReservationEndDateTime: new Date("11/11/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "ABC-234",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG2Lvl3.png",
    //     FloorPlanDescription: "CG2 Level 3",
    //     FloorName: "Level 3",
    //     CheckInDateTime: new Date("11/11/23 8:00"),
    //     CheckOutDateTime: new Date("11/11/23 19:00")
    // },
    // {
    //    ReservationId: 8,
    //     ParkingSpaceId: 4002,
    //     SpaceName: "EB3. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Cebu ebloc 3",
    //     PeopleKey: 600617,
    //     LastName: "Cruz",
    //     FirstName: "Alex",
    //     Eid: "alex.cruz",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/16/23 8:00"),
    //     ReservationEndDateTime: new Date("11/16/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Thursday",
    //     PlateNbr: "ABC-234",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Ebloc",
    //     FloorPlanURL: "",
    //     FloorPlanDescription: "",
    //     FloorName: "",
    //     CheckInDateTime: new Date("11/16/23 8:00"),
    //     CheckOutDateTime: new Date("11/16/23 19:00")
    // },
    // {
    //    ReservationId: 9,
    //     ParkingSpaceId: 5001,
    //     SpaceName: "UT. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 600617,
    //     LastName: "Cruz",
    //     FirstName: "Alex",
    //     Eid: "alex.cruz",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/17/23 8:00"),
    //     ReservationEndDateTime: new Date("11/17/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "ABC-234",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/17/23 8:00"),
    //     CheckOutDateTime: new Date("11/17/23 19:00")
    // },
    // {
    //    ReservationId: 10,
    //     ParkingSpaceId: 1001,
    //     SpaceName: "CG1. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 600617,
    //     LastName: "Cruz",
    //     FirstName: "Alex",
    //     Eid: "alex.cruz",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/9/23 23:50"),
    //     ReservationEndDateTime: new Date("11/10/23 2:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "ABC-234",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/9/23 23:50"),
    //     CheckOutDateTime: new Date("11/10/23 2:00")
    // },
    // {
    //    ReservationId: 11,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 617999,
    //     LastName: "Santos",
    //     FirstName: "Quinn",
    //     Eid: "quinn.santos",
    //     CareerLevel: "Associate Director",
    //     ReservationStartDateTime: new Date("11/10/23 8:00"),
    //     ReservationEndDateTime: new Date("11/10/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "XZY-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/10/23 8:00"),
    //     CheckOutDateTime: new Date("11/10/23 19:00")
    // },
    // {
    //    ReservationId: 12,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 617999,
    //     LastName: "Santos",
    //     FirstName: "Quinn",
    //     Eid: "quinn.santos",
    //     CareerLevel: "Associate Director",
    //     ReservationStartDateTime: new Date("11/12/23 8:00"),
    //     ReservationEndDateTime: new Date("11/12/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Sunday",
    //     PlateNbr: "XZY-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/12/23 8:00"),
    //     CheckOutDateTime: new Date("11/12/23 19:00")
    // },
    // {
    //    ReservationId: 13,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 617999,
    //     LastName: "Santos",
    //     FirstName: "Quinn",
    //     Eid: "quinn.santos",
    //     CareerLevel: "Associate Director",
    //     ReservationStartDateTime: new Date("11/14/23 8:00"),
    //     ReservationEndDateTime: new Date("11/14/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Tuesday",
    //     PlateNbr: "XZY-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/14/23 8:00"),
    //     CheckOutDateTime: new Date("11/14/23 19:00")
    // },
    // {
    //    ReservationId: 14,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 617999,
    //     LastName: "Santos",
    //     FirstName: "Quinn",
    //     Eid: "quinn.santos",
    //     CareerLevel: "Associate Director",
    //     ReservationStartDateTime: new Date("11/16/23 8:00"),
    //     ReservationEndDateTime: new Date("11/16/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Thursday",
    //     PlateNbr: "XZY-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/16/23 8:00"),
    //     CheckOutDateTime: new Date("11/16/23 19:00")
    // },
    // {
    //    ReservationId: 15,
    //     ParkingSpaceId: 5001,
    //     SpaceName: "UT. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 617999,
    //     LastName: "Santos",
    //     FirstName: "Quinn",
    //     Eid: "quinn.santos",
    //     CareerLevel: "Associate Director",
    //     ReservationStartDateTime: new Date("10/17/23 8:00"),
    //     ReservationEndDateTime: new Date("10/17/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "XZY-123",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("10/17/23 8:00"),
    //     CheckOutDateTime: new Date("10/17/23 19:00")
    // },
    // {
    //    ReservationId: 16,
    //     ParkingSpaceId: 3001,
    //     SpaceName: "CG3. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "GS",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("11/13/23 8:00"),
    //     ReservationEndDateTime: new Date("11/13/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Monday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/13/23 8:00"),
    //     CheckOutDateTime: new Date("11/13/23 19:00")
    // },
    // {
    //    ReservationId: 17,
    //     ParkingSpaceId: 2001,
    //     SpaceName: "CG2. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 2",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("11/11/23 8:00"),
    //     ReservationEndDateTime: new Date("11/11/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG2Lvl3.png",
    //     FloorPlanDescription: "CG2 Level 3",
    //     FloorName: "Level 3",
    //     CheckInDateTime: new Date("11/11/23 8:00"),
    //     CheckOutDateTime: new Date("11/11/23 19:00")
    // },
    // {
    //    ReservationId: 18,
    //     ParkingSpaceId: 4001,
    //     SpaceName: "EB3. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "GS",
    //     FacilityName: "Cebu ebloc 3",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("11/15/23 8:00"),
    //     ReservationEndDateTime: new Date("11/15/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Wednesday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Ebloc",
    //     FloorPlanURL: "",
    //     FloorPlanDescription: "",
    //     FloorName: "",
    //     CheckInDateTime: new Date("11/15/23 8:00"),
    //     CheckOutDateTime: new Date("11/15/23 19:00")
    // },
    // {
    //    ReservationId: 19,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("10/18/23 8:00"),
    //     ReservationEndDateTime: new Date("10/18/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Canceled",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("10/18/23 8:00"),
    //     CheckOutDateTime: new Date("10/18/23 19:00")
    // },
    // {
    //    ReservationId: 20,
    //     ParkingSpaceId: 1002,
    //     SpaceName: "CG1. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 618887,
    //     LastName: "Reyes",
    //     FirstName: "Mar",
    //     Eid: "mar.reyes",
    //     CareerLevel: "Manager",
    //     ReservationStartDateTime: new Date("11/10/23 8:00"),
    //     ReservationEndDateTime: new Date("11/10/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "CCC-156",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/10/23 8:00"),
    //     CheckOutDateTime: new Date("11/10/23 19:00")
    // },
    // {
    //    ReservationId: 21,
    //     ParkingSpaceId: 3002,
    //     SpaceName: "CG3. Slot 2",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Ops",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 788442,
    //     LastName: "Tan",
    //     FirstName: "Amor",
    //     Eid: "amor.tan",
    //     CareerLevel: "Team Lead",
    //     ReservationStartDateTime: new Date("11/14/23 8:00"),
    //     ReservationEndDateTime: new Date("11/14/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Tuesday",
    //     PlateNbr: "KGE-990",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/14/23 8:00"),
    //     CheckOutDateTime: new Date("11/14/23 19:00")
    // },
    // {
    //    ReservationId: 22,
    //     ParkingSpaceId: 2002,
    //     SpaceName: "CG2. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Robinson Cybergate 2",
    //     PeopleKey: 788442,
    //     LastName: "Tan",
    //     FirstName: "Amor",
    //     Eid: "amor.tan",
    //     CareerLevel: "Team Lead",
    //     ReservationStartDateTime: new Date("11/12/23 8:00"),
    //     ReservationEndDateTime: new Date("11/12/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Sunday",
    //     PlateNbr: "KGE-990",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG2Lvl3.png",
    //     FloorPlanDescription: "CG2 Level 3",
    //     FloorName: "Level 3",
    //     CheckInDateTime: new Date("11/12/23 8:00"),
    //     CheckOutDateTime: new Date("11/12/23 19:00")
    // },
    // {
    //    ReservationId: 23,
    //     ParkingSpaceId: 4002,
    //     SpaceName: "EB3. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Cebu ebloc 3",
    //     PeopleKey: 788442,
    //     LastName: "Tan",
    //     FirstName: "Amor",
    //     Eid: "amor.tan",
    //     CareerLevel: "Team Lead",
    //     ReservationStartDateTime: new Date("11/16/23 8:00"),
    //     ReservationEndDateTime: new Date("11/16/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Thursday",
    //     PlateNbr: "KGE-990",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Ebloc",
    //     FloorPlanURL: "",
    //     FloorPlanDescription: "",
    //     FloorName: "",
    //     CheckInDateTime: new Date("11/16/23 8:00"),
    //     CheckOutDateTime: new Date("11/16/23 19:00")
    // },
    // {
    //    ReservationId: 24,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 788442,
    //     LastName: "Tan",
    //     FirstName: "Amor",
    //     Eid: "amor.tan",
    //     CareerLevel: "Team Lead",
    //     ReservationStartDateTime: new Date("11/3/23 8:00"),
    //     ReservationEndDateTime: new Date("11/3/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "KGE-990",
    //     ReservationStatus: "Canceled",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/3/23 8:00"),
    //     CheckOutDateTime: new Date("11/3/23 19:00")
    // },
    // {
    //    ReservationId: 25,
    //     ParkingSpaceId: 1002,
    //     SpaceName: "CG1. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 788442,
    //     LastName: "Tan",
    //     FirstName: "Amor",
    //     Eid: "amor.tan",
    //     CareerLevel: "Team Lead",
    //     ReservationStartDateTime: new Date("11/10/23 8:00"),
    //     ReservationEndDateTime: new Date("11/10/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "KGE-990",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/10/23 8:00"),
    //     CheckOutDateTime: new Date("11/10/23 19:00")
    // },
    // {
    //    ReservationId: 26,
    //     ParkingSpaceId: 5001,
    //     SpaceName: "UT. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("10/9/23 8:00"),
    //     ReservationEndDateTime: new Date("10/9/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("10/9/23 8:00"),
    //     CheckOutDateTime: new Date("10/9/23 19:00")
    // },
    // {
    //    ReservationId: 27,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("9/10/23 8:00"),
    //     ReservationEndDateTime: new Date("9/10/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Sunday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("9/10/23 8:00"),
    //     CheckOutDateTime: new Date("9/10/23 19:00")
    // },
    // {
    //    ReservationId: 28,
    //     ParkingSpaceId: 5001,
    //     SpaceName: "UT. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("9/13/23 8:00"),
    //     ReservationEndDateTime: new Date("9/13/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Wednesday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Canceled",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("9/13/23 8:00"),
    //     CheckOutDateTime: new Date("9/13/23 19:00")
    // },
    // {
    //    ReservationId: 29,
    //     ParkingSpaceId: 5001,
    //     SpaceName: "UT. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("9/15/23 8:00"),
    //     ReservationEndDateTime: new Date("9/15/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("9/15/23 8:00"),
    //     CheckOutDateTime: new Date("9/15/23 19:00")
    // },
    // {
    //    ReservationId: 30,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("9/18/23 8:00"),
    //     ReservationEndDateTime: new Date("9/18/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Monday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Canceled",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("9/18/23 8:00"),
    //     CheckOutDateTime: new Date("9/18/23 19:00")
    // },
    // {
    //    ReservationId: 31,
    //     ParkingSpaceId: 3002,
    //     SpaceName: "CG3. Slot 2",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Ops",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/14/23 8:00"),
    //     ReservationEndDateTime: new Date("11/14/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Tuesday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/14/23 8:00"),
    //     CheckOutDateTime: new Date("11/14/23 19:00")
    // },
    // {
    //    ReservationId: 32,
    //     ParkingSpaceId: 2001,
    //     SpaceName: "CG2. Slot 1",
    //     //SpaceStatus: "Vacant",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 2",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/11/23 8:00"),
    //     ReservationEndDateTime: new Date("11/11/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG2Lvl3.png",
    //     FloorPlanDescription: "CG2 Level 3",
    //     FloorName: "Level 3",
    //     CheckInDateTime: new Date("11/11/23 8:00"),
    //     CheckOutDateTime: new Date("11/11/23 19:00")
    // },
    // {
    //    ReservationId: 33,
    //     ParkingSpaceId: 4002,
    //     SpaceName: "EB3. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Cebu ebloc 3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/16/23 8:00"),
    //     ReservationEndDateTime: new Date("11/16/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Thursday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Ebloc",
    //     FloorPlanURL: "",
    //     FloorPlanDescription: "",
    //     FloorName: "",
    //     CheckInDateTime: new Date("11/16/23 8:00"),
    //     CheckOutDateTime: new Date("11/16/23 19:00")
    // },
    // {
    //    ReservationId: 34,
    //     ParkingSpaceId: 5002,
    //     SpaceName: "UT. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "GS",
    //     FacilityName: "Uptown Bonifacio Towers 2/3",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/18/23 8:00"),
    //     ReservationEndDateTime: new Date("11/18/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Saturday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Canceled",
    //     ClusterName: "Uptown",
    //     FloorPlanURL: "assets/map/UTB4.png",
    //     FloorPlanDescription: "UT2 B4 Layout",
    //     FloorName: "B4",
    //     CheckInDateTime: new Date("11/18/23 8:00"),
    //     CheckOutDateTime: new Date("11/18/23 19:00")
    // },
    // {
    //    ReservationId: 35,
    //     ParkingSpaceId: 1002,
    //     SpaceName: "CG1. Slot 2",
    //     //SpaceStatus: "Occupied",
    //     SpaceEntity: "Tech",
    //     FacilityName: "Robinson Cybergate 1",
    //     PeopleKey: 637849,
    //     LastName: "Santos",
    //     FirstName: "Manolo",
    //     Eid: "manolo.santos",
    //     CareerLevel: "Accenture Leadership",
    //     ReservationStartDateTime: new Date("11/10/23 8:00"),
    //     ReservationEndDateTime: new Date("11/10/23 19:00"),
    //     EAName: "",
    //     DayofWeek: "Friday",
    //     PlateNbr: "HRT-322",
    //     ReservationStatus: "Completed",
    //     ClusterName: "Cybergate",
    //     FloorPlanURL: "assets/map/CG1Lvl4.png",
    //     FloorPlanDescription: "CG1 Level 4",
    //     FloorName: "Level 4",
    //     CheckInDateTime: new Date("11/10/23 8:00"),
    //     CheckOutDateTime: new Date("11/10/23 19:00")
    // }
]